name:                forum-crawler
version:             0.1.0.0
github:              "vapaj/forum-crawler"
license:             BSD3

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- http-conduit
library:
  source-dirs: src

executables:
  forum-crawler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forum-crawler
    - bytestring
    - tagsoup
    - text
    - safe
tests:
  forum-crawler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forum-crawler
